/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.sinou.android.kotlin.openapi.model

import org.sinou.android.kotlin.openapi.model.RestNodeLocator
import org.sinou.android.kotlin.openapi.model.TreeNodeType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param locator 
 * @param type 
 * @param contentType 
 * @param templateUuid 
 */


data class RestIncomingNode (

    @Json(name = "Locator")
    val locator: RestNodeLocator,

    @Json(name = "Type")
    val type: TreeNodeType = TreeNodeType.UNKNOWN,

    @Json(name = "ContentType")
    val contentType: kotlin.String? = null,

    @Json(name = "TemplateUuid")
    val templateUuid: kotlin.String? = null

) {


}

