/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.sinou.android.kotlin.openapi.model

import org.sinou.android.kotlin.openapi.model.MetaUpdateOp
import org.sinou.android.kotlin.openapi.model.RestUserMeta

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param operation 
 * @param userMeta 
 */


data class RestMetaUpdate (

    @Json(name = "Operation")
    val operation: MetaUpdateOp = MetaUpdateOp.PUT,

    @Json(name = "UserMeta")
    val userMeta: RestUserMeta

) {


}

