/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.sinou.android.kotlin.openapi.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.sinou.android.kotlin.openapi.model.RestPerformActionResponse
import org.sinou.android.kotlin.openapi.model.RestActionStatus
import org.sinou.android.kotlin.openapi.model.RestBackgroundAction
import org.sinou.android.kotlin.openapi.model.RestNode

class RestPerformActionResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RestPerformActionResponse
        //val modelInstance = RestPerformActionResponse()

        // to test the property `affectedNodes`
        should("test affectedNodes") {
            // uncomment below to test the property
            //modelInstance.affectedNodes shouldBe ("TODO")
        }

        // to test the property `backgroundActions`
        should("test backgroundActions") {
            // uncomment below to test the property
            //modelInstance.backgroundActions shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

    }
}
