/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.sinou.android.kotlin.openapi.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.sinou.android.kotlin.openapi.model.RestNamespaceValuesOperation
import org.sinou.android.kotlin.openapi.model.RestNsOp

class RestNamespaceValuesOperationTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RestNamespaceValuesOperation
        //val modelInstance = RestNamespaceValuesOperation()

        // to test the property `operation`
        should("test operation") {
            // uncomment below to test the property
            //modelInstance.operation shouldBe ("TODO")
        }

        // to test the property `propertyValues`
        should("test propertyValues") {
            // uncomment below to test the property
            //modelInstance.propertyValues shouldBe ("TODO")
        }

    }
}
