/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.sinou.android.kotlin.openapi.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.sinou.android.kotlin.openapi.model.RestNodeUpdates
import org.sinou.android.kotlin.openapi.model.RestMetaToggle
import org.sinou.android.kotlin.openapi.model.RestMetaUpdate

class RestNodeUpdatesTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RestNodeUpdates
        //val modelInstance = RestNodeUpdates()

        // to test the property `bookmark`
        should("test bookmark") {
            // uncomment below to test the property
            //modelInstance.bookmark shouldBe ("TODO")
        }

        // to test the property `contentLock`
        should("test contentLock") {
            // uncomment below to test the property
            //modelInstance.contentLock shouldBe ("TODO")
        }

        // to test the property `metaUpdates`
        should("test metaUpdates") {
            // uncomment below to test the property
            //modelInstance.metaUpdates shouldBe ("TODO")
        }

    }
}
