/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.sinou.android.kotlin.openapi.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.sinou.android.kotlin.openapi.model.RestTemplate
import org.sinou.android.kotlin.openapi.model.RestTemplateNode
import org.sinou.android.kotlin.openapi.model.ServiceResourcePolicy

class RestTemplateTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RestTemplate
        //val modelInstance = RestTemplate()

        // to test the property `editable`
        should("test editable") {
            // uncomment below to test the property
            //modelInstance.editable shouldBe ("TODO")
        }

        // to test the property `label`
        should("test label") {
            // uncomment below to test the property
            //modelInstance.label shouldBe ("TODO")
        }

        // to test the property `node`
        should("test node") {
            // uncomment below to test the property
            //modelInstance.node shouldBe ("TODO")
        }

        // to test the property `policies`
        should("test policies") {
            // uncomment below to test the property
            //modelInstance.policies shouldBe ("TODO")
        }

        // to test the property `UUID`
        should("test UUID") {
            // uncomment below to test the property
            //modelInstance.UUID shouldBe ("TODO")
        }

    }
}
