/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.sinou.android.kotlin.openapi.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.sinou.android.kotlin.openapi.model.RestCreateRequest
import org.sinou.android.kotlin.openapi.model.RestIncomingNode

class RestCreateRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RestCreateRequest
        //val modelInstance = RestCreateRequest()

        // to test the property `inputs`
        should("test inputs") {
            // uncomment below to test the property
            //modelInstance.inputs shouldBe ("TODO")
        }

        // to test the property `recursive`
        should("test recursive") {
            // uncomment below to test the property
            //modelInstance.recursive shouldBe ("TODO")
        }

    }
}
