/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.sinou.android.kotlin.openapi.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.sinou.android.kotlin.openapi.model.RestIncomingNode
import org.sinou.android.kotlin.openapi.model.RestNodeLocator
import org.sinou.android.kotlin.openapi.model.TreeNodeType

class RestIncomingNodeTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RestIncomingNode
        //val modelInstance = RestIncomingNode()

        // to test the property `locator`
        should("test locator") {
            // uncomment below to test the property
            //modelInstance.locator shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `contentType`
        should("test contentType") {
            // uncomment below to test the property
            //modelInstance.contentType shouldBe ("TODO")
        }

        // to test the property `templateUuid`
        should("test templateUuid") {
            // uncomment below to test the property
            //modelInstance.templateUuid shouldBe ("TODO")
        }

    }
}
