/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.sinou.android.kotlin.openapi.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.sinou.android.kotlin.openapi.model.RestNodeCollection
import org.sinou.android.kotlin.openapi.model.RestNode
import org.sinou.android.kotlin.openapi.model.RestPagination
import org.sinou.android.kotlin.openapi.model.TreeSearchFacet

class RestNodeCollectionTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RestNodeCollection
        //val modelInstance = RestNodeCollection()

        // to test the property `nodes`
        should("test nodes") {
            // uncomment below to test the property
            //modelInstance.nodes shouldBe ("TODO")
        }

        // to test the property `facets`
        should("test facets") {
            // uncomment below to test the property
            //modelInstance.facets shouldBe ("TODO")
        }

        // to test the property `pagination`
        should("test pagination") {
            // uncomment below to test the property
            //modelInstance.pagination shouldBe ("TODO")
        }

    }
}
