/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.sinou.android.kotlin.openapi.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.sinou.android.kotlin.openapi.model.RestActionParameters
import org.sinou.android.kotlin.openapi.model.JobsTaskStatus
import org.sinou.android.kotlin.openapi.model.RestNodeLocator

class RestActionParametersTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RestActionParameters
        //val modelInstance = RestActionParameters()

        // to test the property `awaitStatus`
        should("test awaitStatus") {
            // uncomment below to test the property
            //modelInstance.awaitStatus shouldBe ("TODO")
        }

        // to test the property `awaitTimeout`
        should("test awaitTimeout") {
            // uncomment below to test the property
            //modelInstance.awaitTimeout shouldBe ("TODO")
        }

        // to test the property `jsonParameters`
        should("test jsonParameters") {
            // uncomment below to test the property
            //modelInstance.jsonParameters shouldBe ("TODO")
        }

        // to test the property `nodes`
        should("test nodes") {
            // uncomment below to test the property
            //modelInstance.nodes shouldBe ("TODO")
        }

        // to test the property `selectionUuid`
        should("test selectionUuid") {
            // uncomment below to test the property
            //modelInstance.selectionUuid shouldBe ("TODO")
        }

        // to test the property `targetNode`
        should("test targetNode") {
            // uncomment below to test the property
            //modelInstance.targetNode shouldBe ("TODO")
        }

    }
}
